In [1]:
import pandas as pd
import numpy as np

In [2]:
df_lab = pd.read_csv('0.csv', names=["STUDBME2","STUDBME1", "Rannnia", "Ayazz","CMP_LAB1","CMP_LAB2","CMP_LAB3", 'loc'], header=None)
df_lab.dropna(axis=0, inplace=True)
df_lab.reset_index(drop=True, inplace=True)

df_doc = pd.read_csv('1.csv', names=["STUDBME2","STUDBME1","Rannnia", "Ayazz","CMP_LAB1","CMP_LAB2","CMP_LAB3", 'loc'], header=None)
df_doc.reset_index(drop=True, inplace=True)


df_hallf = pd.read_csv('2.csv', names=["STUDBME2","STUDBME1", "Rannnia", "Ayazz","CMP_LAB1","CMP_LAB2","CMP_LAB3", 'loc'], header=None)
df_hallf.dropna(axis=0, inplace=True)
df_hallf.reset_index(drop=True, inplace=True)

df_cl2 = pd.read_csv('3.csv', names=["STUDBME2","STUDBME1", "Rannnia", "Ayazz","CMP_LAB1","CMP_LAB2","CMP_LAB3", 'loc'], header=None)
df_cl2.dropna(axis=0, inplace=True)
df_cl2.reset_index(drop=True, inplace=True)

df_co1 = pd.read_csv('4.csv', names=["STUDBME2","STUDBME1", "Rannnia", "Ayazz","CMP_LAB1","CMP_LAB2","CMP_LAB3", 'loc'], header=None)
df_co1.dropna(axis=0, inplace=True)
df_co1.reset_index(drop=True, inplace=True)


df_lab2 = pd.read_csv('5.csv', names=["STUDBME2","STUDBME1", "Rannnia", "Ayazz","CMP_LAB1","CMP_LAB2","CMP_LAB3", 'loc'], header=None)
df_lab2.reset_index(drop=True, inplace=True)

In [5]:
display(df_doc)

STUDBME2  STUDBME1  Rannnia  Ayazz  CMP_LAB1  CMP_LAB2  CMP_LAB3  loc
0        -76       -67      -87    -71       -91       -87       -85    1
1        -86       -68      -87    -71       -91       -87       -85    1
2        -74       -68      -78    -72       -91       -87       -85    1
3        -74       -60      -78    -72       -91       -87       -85    1
4        -72       -64      -78    -70       -85       -87       -85    1
..       ...       ...      ...    ...       ...       ...       ...  ...
75       -74       -70      -87    -77       -90       -77       -92    1
76       -74       -66      -87    -59       -90       -77       -92    1
77       -77       -66      -87    -73       -85       -77       -92    1
78       -77       -66      -87    -73       -85       -77       -92    1
79       -78       -62      -87    -73       -85       -77       -92    1

[80 rows x 8 columns]

In [6]:
dfs = [df_lab, df_doc, df_hallf, df_cl2, df_co1, df_lab2]
df = pd.concat(dfs, ignore_index=True)
df.drop("Rannnia", axis=1, inplace=True)
display(df)

STUDBME2  STUDBME1  Ayazz  CMP_LAB1  CMP_LAB2  CMP_LAB3  loc
0         -80       -53    -86       -92       -78       -84    0
1         -80       -54    -86       -92       -78       -84    0
2         -85       -54    -86       -92       -78       -84    0
3         -85       -54    -81       -92       -78       -84    0
4         -80       -54    -87       -92       -78       -84    0
..        ...       ...    ...       ...       ...       ...  ...
549       -68       -26    -83       -78       -75       -80    5
550       -72       -32    -83       -78       -75       -80    5
551       -69       -32    -83       -78       -75       -80    5
552       -67       -50    -83       -78       -75       -86    5
553       -71       -41    -83       -88       -75       -86    5

[554 rows x 7 columns]

In [7]:
df=df.sample(frac=1).reset_index(drop=True)

In [8]:
from sklearn.model_selection import train_test_split, GridSearchCV, cross_validate
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import precision_score, recall_score, confusion_matrix, roc_auc_score, classification_report, accuracy_score

In [9]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 42)

In [11]:
pd.Series(y_train).value_counts()

2    75
5    73
3    73
4    70
0    64
1    60
dtype: int64

In [12]:
#sc = StandardScaler()
#X_train = sc.fit_transform(X_train)
#X_test = sc.transform(X_test)

In [13]:
classifier = RandomForestClassifier(n_estimators = 20, max_depth=10)
#classifier = LogisticRegression(multi_class='multinomial',solver ='newton-cg',max_iter=1000)
#classifier = SVC(probability=True, gamma=0.001, kernel='poly')
#classifier = GaussianNB()
classifier.fit(X_train, y_train)

RandomForestClassifier(max_depth=10, n_estimators=20)

In [14]:
res = classifier.predict(X_test)

In [15]:
cm = confusion_matrix(y_test, res)
print(cm)
accuracy_score(y_test, res)

[[25  0  0  0  0  0]
 [ 0 20  0  0  0  0]
 [ 0  0 18  0  0  0]
 [ 0  0  0 27  0  0]
 [ 0  0  1  0 28  0]
 [ 0  0  0  0  0 20]]


0.9928057553956835

In [16]:
print(classification_report(y_test, res))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        25
           1       1.00      1.00      1.00        20
           2       0.95      1.00      0.97        18
           3       1.00      1.00      1.00        27
           4       1.00      0.97      0.98        29
           5       1.00      1.00      1.00        20

    accuracy                           0.99       139
   macro avg       0.99      0.99      0.99       139
weighted avg       0.99      0.99      0.99       139



In [17]:
import pickle
import joblib

#save the model
filename = 'model2.sav'
joblib.dump(classifier, filename)

['model2.sav']

In [18]:
#load the model
loaded_model = joblib.load(filename)
result = loaded_model.score(X_test, y_test)
print(result)

0.9928057553956835


In [19]:
classifier.predict(sc.transform([[-51,-73,-86,-73,-71,-71]]))

NameError: name 'sc' is not defined